app:
  cors:
    allowed-origins: http://localhost:5173,http://192.168.50.190:5173
    allow-credentials: false

aws:
  region: us-west-1
  s3:
    bucket: stacta-images-prod
  cdn:
    base-url:

spring:
  jpa:
    properties:
      hibernate:
        format_sql: false

  flyway:
    repair-on-migrate: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO